---
# tasks file for ansible-role-win-sqlserver

- name: Get wuauserv start_mode
  ansible.windows.win_service:
    name: wuauserv
  register: wuauserv_state
  
- debug:
    var: wuauserv_state.start_mode

- name: Set wuauserv start_mode=manual
  ansible.windows.win_service:
    name: wuauserv
    start_mode: manual
  register: wuauserv_state_modified
  when: wuauserv_state.start_mode == 'disabled'



- name: Powershell | Install Required Powershell Modules
  win_psmodule: 
    name: '{{ item }}' 
    state: present
  with_items:
    - SQLServerDsc
    - StorageDsc
    - ServerManager
    - dbatools
    - xNetworking

- name: Download SQL Server ISO
  win_get_url:
    url: '{{ sql_server_iso_url }}'
    dest: C:\Windows\Temp\sql_server.iso
    force: no

- name: Sleep for 2 seconds and continue with play
  wait_for:
    timeout: 2
  delegate_to: localhost

- name: Mount SQL Server ISO
  win_disk_image:
    image_path: C:\Windows\Temp\sql_server.iso
    state: present
  register: disk_image_out

- name: Sleep for 2 seconds and continue with play
  wait_for:
    timeout: 2
  delegate_to: localhost

# mount_path[] !!!

- name: Install SQL Server (ansible < 2.10)
  win_dsc:
    resource_name: SQLSetup
    Action: Install
    SourcePath: '{{ disk_image_out.mount_path }}'
    InstanceName: '{{ sql_server_instance_name }}'
    InstallSharedDir: C:\Program Files\Microsoft SQL Server
    InstallSharedwowDir: C:\Program Files (x86)\Microsoft SQL Server
    InstanceDir: C:\Program Files\Microsoft SQL Server
    SQLUserDBDir: '{{ sql_server_dir_user_db }}'
    SQLUserDBLogDir: '{{ sql_server_dir_user_log }}'
    SQLTempDBDir: '{{ sql_server_dir_temp_db }}'
    SQLTempDBLogDir: '{{ sql_server_dir_temp_log }}'
    Features: '{{ sql_server_install_features }}'
    SQLCollation: '{{ sql_server_collation }}'
    BrowserSvcStartupType: Automatic
    SQLSysAdminAccounts: '{{ sql_server_sysadminaccounts }}'
    SecurityMode: SQL
    SAPwd_username: sa
    SAPwd_password: '{{ sql_server_sa_password }}'
    PsDscRunAsCredential_username: '{{ ansible_user }}'
    PsDscRunAsCredential_password: '{{ ansible_password }}'
  no_log: false
  when: ansible_version.full is version_compare('2.10', '<')

- name: Install SQL Server (ansible >= 2.10)
  win_dsc:
    resource_name: SQLSetup
    Action: Install
    SourcePath: '{{ disk_image_out.mount_paths[0] }}'
    InstanceName: '{{ sql_server_instance_name }}'
    InstallSharedDir: C:\Program Files\Microsoft SQL Server
    InstallSharedwowDir: C:\Program Files (x86)\Microsoft SQL Server
    InstanceDir: C:\Program Files\Microsoft SQL Server
    SQLUserDBDir: '{{ sql_server_dir_user_db }}'
    SQLUserDBLogDir: '{{ sql_server_dir_user_log }}'
    SQLTempDBDir: '{{ sql_server_dir_temp_db }}'
    SQLTempDBLogDir: '{{ sql_server_dir_temp_log }}'
    Features: '{{ sql_server_install_features }}'
    SQLCollation: '{{ sql_server_collation }}'
    BrowserSvcStartupType: Automatic
    SQLSysAdminAccounts: '{{ sql_server_sysadminaccounts }}'
    SecurityMode: SQL
    SAPwd_username: sa
    SAPwd_password: '{{ sql_server_sa_password }}'
    PsDscRunAsCredential_username: '{{ ansible_user }}'
    PsDscRunAsCredential_password: '{{ ansible_password }}'
  no_log: false
  when: ansible_version.full is version_compare('2.10', '>=')
    
- name: Umount SQL Server ISO
  win_disk_image:
    image_path: C:\Windows\Temp\sql_server.iso
    state: absent

- name: Restore wuauserv start_mode={{ wuauserv_state.start_mode }}
  ansible.windows.win_service:
    name: wuauserv
    start_mode: '{{ wuauserv_state.start_mode }}'
  when: wuauserv_state_modified.changed